# Run Overcommit within a Bundler context using this repo's Gemfile
gemfile: Gemfile

PreCommit:
  BundleCheck:
    enabled: true

  ExecutePermissions:
    enabled: true
    exclude:
      - 'bin/slim-lint'

  HardTabs:
    enabled: true
    exclude:
      - 'spec/slim_lint/linter/tab_spec.rb'

  RuboCop:
    enabled: true

  TrailingWhitespace:
    enabled: true

  YamlSyntax:
    enabled: true
